import Sqlite from 'better-sqlite3';
import { Dict, Definition } from './interface';
export declare class Model {
    db: Sqlite.Database;
    dbFile: string;
    table: string;
    definition: Definition;
    attributes: Dict;
    changed: Dict;
    pk: string;
    constructor(definition?: Definition, dbFile?: string, table?: string);
    initialize(): Model;
    attr(name: string, value: any): void;
    clone<T extends Model>(instance: T): T;
    instance(data: Dict): Model;
    toObject(): Dict;
    toJSON(): Dict;
    exec(sql: string): any;
    find(where: Dict, options?: Dict): Model[];
    findOne(where: Dict, options?: Dict): Model | null;
    findAll(where: Dict, options?: Dict): Model[];
    findById(id: bigint | number): Model | null;
    findByIds(ids: number[]): Model[];
    insert(data: Dict): Model;
    update(where: Dict, data: Dict): any;
    updateAttributes(data: Dict): Model;
    upsert(data: Dict): Model;
    save(): Model;
    deleteById(id: number): boolean;
    delete(where: Dict): Sqlite.RunResult;
}
